spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:produtosdb
    username: sa
    password: passh2
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console